[build]
  publish = "google-login-clone"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# NOTE: This is FRONTEND config backup
# To deploy frontend: rename this to netlify.toml
# To deploy admin GUI: use current netlify.toml (admin-gui-clean)

[context.production.environment]
  SITE_URL = "https://google-login-clone-demo.netlify.app" 