[build]
  publish = "google-login-clone"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# NOTE: This is FRONTEND config  
# Repository: https://github.com/tigerads1998/login-clone
# Branch: main
# Publish directory: google-login-clone
# Site name: google-login-clone-demo

[context.production.environment]
  SITE_URL = "https://google-login-clone-demo.netlify.app" 